### ISSUE TITLE
External api implementation

### ISSUE THREAD

**Issue by deshmukh-shekhar** [castai/audit-logs-receiver#48]
I have implemented audit log exporter in k8s then how can i implement proprietary API for external logging system in helm chart.

**Comment by fals** [comment]
@deshmukh-shekhar could you elaborate your question? If I understood you want to pull metrics from the API instead?

**Comment by fals** [comment]
@deshmukh-shekhar this component is a simple receiver you can deploy in your cluster that would allow exporting it to any system compatible. In other others, our receiver needs an exported for Datadog:

- Docs about this component: https://docs.cast.ai/docs/audit-log-exporter#the-architecture-of-the-solution
- DataDog exported: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter

You need to combine our component with DataDog Exporter.

**Comment by fals** [comment]
@deshmukh-shekhar I will close the issue as I provided the information needed to setup. You can always reach us out on our [community slack](https://castai-community.slack.com/ssb/redirect) for questions related to our product.
